# Generated by Django 5.1.3 on 2024-11-15 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.CharField(max_length=20, unique=True)),
                ('Course_Name', models.CharField(max_length=255)),
                ('Semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('Department', models.CharField(choices=[('Computer Engineering', 'Computer Engineering'), ('Artificial Intelligence and Data Science', 'Artificial Intelligence and Data Science'), ('Electronics and Computer Science', 'Electronics and Computer Science'), ('Mechanical Engineering', 'Mechanical Engineering')], max_length=100)),
                ('Syllabus', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
