# Generated by Django 5.1.3 on 2024-11-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
