# Generated by Django 5.1.3 on 2024-11-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_id_alter_course_courseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_Outcomes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
