# Generated by Django 5.1.3 on 2024-11-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_outcomes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Course_Outcomes',
        ),
        migrations.AddField(
            model_name='course',
            name='Syllabus_source',
            field=models.ImageField(blank=True, null=True, upload_to='syllabus_images/'),
        ),
    ]
